select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Control_Mode"
    name: "${entities_name_prefix}-Battery Control Mode"
    address: 98
    value_type: U_WORD
    optionsmap:
      "Lead Acid": 0
      "Lithium (BMS)": 1


  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Lithium_Type"
    name: "${entities_name_prefix}-Battery Lithium Type"
    address: 223
    value_type: U_WORD
    optionsmap:
      "Pylon / Solax / Universal CAN Protocol (CAN)": 0x0000
      "Tianbangda RS485 Modbus": 0x0001
      "KOK Protocol": 0x0002
      "Keith Protocol": 0x0003
      "Topband Protocol": 0x0004
      "Pylontech 485 Protocol": 0x0005
      "Jelais 485 Protocol": 0x0006
      "Sunwoda 485 Protocol": 0x0007
      "Xinruineng 485 Protocol": 0x0008
      "Tianbangda 485 Protocol": 0x0009
      "Shenggao Electric CAN Protocol": 0x000A


number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Equalization_voltage"
    name: "${entities_name_prefix}-Battery Equalization voltage"
    address: 99
    unit_of_measurement: V
    value_type: U_WORD
    multiply: 100.0
    min_value: 38.00
    max_value: 61.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Absorption_voltage"
    name: "${entities_name_prefix}-Battery Absorption voltage"
    address: 100
    unit_of_measurement: V
    value_type: U_WORD
    multiply: 100.0
    min_value: 38.00
    max_value: 61.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Float_voltage"
    name: "${entities_name_prefix}-Battery Float voltage"
    address: 101
    unit_of_measurement: V
    value_type: U_WORD
    multiply: 100.0
    min_value: 38.00
    max_value: 61.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Equalization_day_cycle"
    name: "${entities_name_prefix}-Battery Equalization Day Cycle"
    address: 105
    unit_of_measurement: days
    value_type: U_WORD
    multiply: 1.0
    min_value: 0.0
    max_value: 90.0

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Equalization_Time"
    name: "${entities_name_prefix}-Battery Equalization Time"
    address: 106
    unit_of_measurement: days
    value_type: U_WORD
    multiply: 1.0
    step: 0.5
    min_value: 0.0
    max_value: 20.0

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_capacity"
    name: "${entities_name_prefix}-Battery capacity"
    address: 102
    unit_of_measurement: Ah
    value_type: U_WORD
    multiply: 1.0
    min_value: 0.00
    max_value: 2000.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Maximum_Charge_Current"
    name: "${entities_name_prefix}-Battery_Maximum Charge Current"
    address: 108
    unit_of_measurement: A
    value_type: U_WORD

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_Battery_Maximum_Discharge_Current"
    name: "${entities_name_prefix}-Battery_Maximum Discharge Current"
    address: 109
    unit_of_measurement: A
    value_type: U_WORD




sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Today Charge of the Battery"
    id: "${entities_id_prefix}_Battery_Today_Charge"
    register_type: holding
    address: 514
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Today Discharge of the Battery"
    id: "${entities_id_prefix}_Battery_Today_Discharge"
    register_type: holding
    address: 515
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 5
    name: "${entities_name_prefix}-Total Charge of the Battery"
    id: "${entities_id_prefix}_Battery_Total_charge"
    register_type: holding
    address: 516
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 5
    name: "${entities_name_prefix}-Total Discharge of the Battery"
    id: "${entities_id_prefix}_Battery_Total_Discharge"
    register_type: holding
    address: 518
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Battery Temperature"
    id: "${entities_id_prefix}_Battery_Temperature"
    register_type: holding
    address: 586
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    value_type: S_WORD
    filters:
      - offset: -1000
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Battery Voltage"
    id: "${entities_id_prefix}_Battery_Voltage"
    register_type: holding
    address: 587
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Battery Capacity"
    id: "${entities_id_prefix}_Battery_Capacity"
    register_type: holding
    address: 588
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Battery Output Power"
    id: "${entities_id_prefix}_Battery_Output_power"
    register_type: holding
    address: 590
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD


  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Battery Output Current"
    id: "${entities_id_prefix}_Battery_Output_Current"
    register_type: holding
    address: 591
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
