sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-External CT Active Power L1"
    id: "${entities_id_prefix}_External_CT_Active_Power_L1"
    register_type: holding
    address: 616
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD



  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-External CT Active Power L2"
    id: "${entities_id_prefix}_External_CT_Active_Power_L2"
    register_type: holding
    address: 617
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD



  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-External CT Active Power L3"
    id: "${entities_id_prefix}_External_CT_Active_Power_L3"
    register_type: holding
    address: 618
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD



  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-External CT Active Power Total"
    id: "${entities_id_prefix}_External_CT_Active_Power_Total"
    register_type: holding
    address: 619
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD



  # External Power Grid - Total Apparent Power
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-External CT Apparent Power Total"
    id: "${entities_id_prefix}_External_CT_Apparent_Power_Total"
    register_type: holding
    address: 620
    unit_of_measurement: "VA"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD
