sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Generator Voltage Phase L1"
    id: "${entities_id_prefix}_Generator_Voltage_Phase_L1"
    register_type: holding
    address: 661
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Generator Voltage Phase L2"
    id: "${entities_id_prefix}_Generator_Voltage_Phase_L2"
    register_type: holding
    address: 662
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Generator Voltage Phase L3"
    id: "${entities_id_prefix}_Generator_Voltage_Phase_L3"
    register_type: holding
    address: 663
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Generator Power L1"
    id: "${entities_id_prefix}_Generator_Power_L1"
    register_type: holding
    address: 664
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Generator Power L2"
    id: "${entities_id_prefix}_Generator_Power_L2"
    register_type: holding
    address: 665
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Generator Power L3"
    id: "${entities_id_prefix}_Generator_Power_L3"
    register_type: holding
    address: 666
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Generator Power Total"
    id: "${entities_id_prefix}_Generator_Power_Total"
    register_type: holding
    address: 667
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD