binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-AC INV Relay" # bit 0
    id: "${entities_id_prefix}_AC_INV_Relay"
    register_type: holding
    address: 552
    bitmask: 0x1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-General - AC Load Relay Reserved" # bit 1
    id: "${entities_id_prefix}_General_AC_Load_Relay_Reserved"
    register_type: holding
    address: 552
    bitmask: 0x2

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-General - AC Grid Relay" # bit 2
    id: "${entities_id_prefix}_General_AC_Grid_Relay"
    register_type: holding
    address: 552
    bitmask: 0x4

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-General - AC Generator Relay" # bit 3
    id: "${entities_id_prefix}_General_AC_Generator_Relay"
    register_type: holding
    address: 552
    bitmask: 0x8

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-General - Turn off/on status"
    id: "${entities_id_prefix}_General_Turn_off_on_status"
    register_type: holding
    address: 551
    bitmask: 0x1

sensor:
  # New - To be Tested
 
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Active Power Regulation"
    id: "${entities_id_prefix}_General_Active_Power_Regulation"
    register_type: holding
    address: 77
    unit_of_measurement: "%"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  # Converts value to percentage

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Reactive Power Regulation"
    id: "${entities_id_prefix}_General_Reactive_Power_Regulation"
    register_type: holding
    address: 78
    unit_of_measurement: "%"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1  # Converts value to percentage

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Apparent Power Regulation"
    id: "${entities_id_prefix}_General_Apparent_Power_Regulation"
    register_type: holding
    address: 79
    unit_of_measurement: ""
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Island Protection Enable"
    id: "${entities_id_prefix}_General_Island_Protection_Enable"
    register_type: holding
    address: 83
    unit_of_measurement: ""
    value_type: S_WORD
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Grid Check Source"
    id: "${entities_id_prefix}_General_Grid_Check_Source"
    register_type: holding
    address: 344
    unit_of_measurement: ""
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - External Current Clamp Phase"
    id: "${entities_id_prefix}_General_External_Current_Clamp_Phase"
    register_type: holding
    address: 144
    unit_of_measurement: ""
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - DC Transformer Temperature"
    id: "${entities_id_prefix}_General_DC_Transformer_Temperature"
    register_type: holding
    address: 540
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - offset: -1000
      - multiply:  0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Heatsink Temperature"
    id: "${entities_id_prefix}_General_Heatsink_Temperature"
    register_type: holding
    address: 541
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - offset: -1000
      - multiply:  0.1

  # New - To be Tested
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Undefined Temperature 1"
    id: "${entities_id_prefix}_General_Undefined_Temperature_1"
    register_type: holding
    address: 542
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - offset: -1000
      - multiply:  0.1

  # New - To be Tested
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Undefined Temperature 2"
    id: "${entities_id_prefix}_General_Undefined_Temperature_2"
    register_type: holding
    address: 543
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - offset: -1000
      - multiply:  0.1

  # New - To be Tested
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Undefined Temperature 3"
    id: "${entities_id_prefix}_General_Undefined_Temperature_3"
    register_type: holding
    address: 544
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - offset: -1000
      - multiply:  0.1


select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Energy Priority"
    id: "${entities_id_prefix}_General_Energy_Priority"
    address: 141
    value_type: U_WORD
    optionsmap:
      "Battery first": 0
      "Load first": 1

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-General - Limit Control Mode"
    id: "${entities_id_prefix}_Limit_Control_Mode"
    address: 142
    value_type: U_WORD
    optionsmap:
      "Selling first": 0
      "Zero export to load": 1
      "Zero export to CT": 2


number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: "${entities_id_prefix}_General_CT_Ratio"
    name: "${entities_name_prefix}-General - CT Ratio"
    address: 347
    value_type: U_WORD
    multiply: 1.0
    min_value: 100.00
    max_value: 10000.00