switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}_Solar_Sell"
    id: "${entities_id_prefix}_Solar_Sell"
    register_type: holding
    address: 145
    bitmask: 1
    entity_category: config
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Grid_Charge"
    id: "${entities_id_prefix}_Grid_Charge"
    register_type: holding
    address: 130
    bitmask: 1
    entity_category: config
    icon: "mdi:toggle-switch"



number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Maximum Battery Grid Charge Current"
    id: "${entities_id_prefix}_Maximum_Battery_Grid_Charge_Current"
    address: 128
    unit_of_measurement: A
    value_type: U_WORD

    # Limit the maximum power output of the grid connection
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Grid Maximum Solar Sell Power"
    id: "${entities_id_prefix}_Grid_Maximum_Solar_Sell_Power"
    unit_of_measurement: W
    address: 143
    value_type: U_WORD

    # Max Solar Sell Power
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Grid Maximum Solar Power"
    id: "${entities_id_prefix}_Grid_Maximum_Solar_Power"
    unit_of_measurement: W
    address: 340
    value_type: U_WORD


sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Grid PF (Power Factor)"
    id: "${entities_id_prefix}_Grid_PF"
    register_type: holding
    address: 621
    unit_of_measurement: "-"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 1000
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Grid Power L1"
    id: "${entities_id_prefix}_Grid_Power_L1"
    register_type: holding
    address: 622
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Grid Power L2"
    id: "${entities_id_prefix}_Grid_Power_L2"
    register_type: holding
    address: 623
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Grid Power L3"
    id: "${entities_id_prefix}_Grid_Power_L3"
    register_type: holding
    address: 624
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Grid Power Total"
    id: "${entities_id_prefix}_Grid_Power_Total"
    register_type: holding
    address: 625
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Grid Total Energy Bought"
    id: "${entities_id_prefix}_Grid_Total_Energy_Bought"
    register_type: holding
    address: 522
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_WORD # Maybe U_DWORD_R is more precise (uses 2 registers)
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Grid Total Energy Sold"
    id: "${entities_id_prefix}_Grid_Total_Energy_Sold"
    register_type: holding
    address: 524
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Grid Daily Energy Bought"
    id: "${entities_id_prefix}_Grid_Daily_Energy_Bought"
    register_type: holding
    address: 520
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Grid Daily Energy Sold"
    id: "${entities_id_prefix}_Grid_Daily_Energy_Sold"
    register_type: holding
    address: 521
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Current L1"
    id: "${entities_id_prefix}_Grid_Current_L1"
    register_type: holding
    address: 630
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Current L2"
    id: "${entities_id_prefix}_Grid_Current_L2"
    register_type: holding
    address: 631
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Current L3"
    id: "${entities_id_prefix}_Grid_Current_L3"
    register_type: holding
    address: 632
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Voltage Phase L1"
    id: "${entities_id_prefix}_Grid_Voltage_Phase_L1"
    register_type: holding
    address: 598
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Voltage Phase L2"
    id: "${entities_id_prefix}_Grid_Voltage_Phase_L2"
    register_type: holding
    address: 599
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Voltage Phase L3"
    id: "${entities_id_prefix}_Grid_Voltage_Phase_L3"
    register_type: holding
    address: 600
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Voltage Line L1L2"
    id: "${entities_id_prefix}_Grid_Voltage_Line_L1L2"
    register_type: holding
    address: 601
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Voltage Line L2"
    id: "${entities_id_prefix}_Grid_Voltage_Line_L2L3"
    register_type: holding
    address: 602
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${entities_name_prefix}-Grid Voltage Line L3L1"
    id: "${entities_id_prefix}_Grid_Voltage_Line_L3L1"
    register_type: holding
    address: 603
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD