sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Load Total Energy"
    id: "${entities_id_prefix}_Load_Total_Energy"
    register_type: holding
    address: 527
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_WORD # Maybe U_DWORD_R is more precise (uses 2 registers)
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 10
    name: "${entities_name_prefix}-Load Daily Energy"
    id: "${entities_id_prefix}_Load_Daily_Energy"
    register_type: holding
    address: 526
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Load Voltage Phase L1"
    id: "${entities_id_prefix}_Load_Voltage_Phase_L1"
    register_type: holding
    address: 644
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Load Voltage Phase L2"
    id: "${entities_id_prefix}_Load_Voltage_Phase_L2"
    register_type: holding
    address: 645
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Load Voltage Phase L3"
    id: "${entities_id_prefix}_Load_Voltage_Phase_L3"
    register_type: holding
    address: 646
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  # To be Tested - It states "No Use" in the Registers References
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Load Current L1"
    id: "${entities_id_prefix}_Load_Current_L1"
    register_type: holding
    address: 647
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    value_type: S_WORD

  # To be Tested - It states "No Use" in the Registers References
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Load Current L2"
    id: "${entities_id_prefix}_Load_Current_L2"
    register_type: holding
    address: 648
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
    value_type: S_WORD

  # To be Tested - It states "No Use" in the Registers References
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Load Current L3"
    id: "${entities_id_prefix}_Load_Current_L3"
    register_type: holding
    address: 649
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Load Active Power L1"
    id: "${entities_id_prefix}_Load_Active_Power_L1"
    register_type: holding
    address: 650
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Load Active Power L2"
    id: "${entities_id_prefix}_Load_Active_Power_L2"
    register_type: holding
    address: 651
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Load Active Power L3"
    id: "${entities_id_prefix}_Load_Active_Power_L3"
    register_type: holding
    address: 652
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Load Active Power Total"
    id: "${entities_id_prefix}_Load_Active_Power_Total"
    register_type: holding
    address: 653
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id_hf}
    name: "${entities_name_prefix}-Load Apparent Power Total"
    id: "${entities_id_prefix}_Load_Apparent_Power_Total"
    register_type: holding
    address: 654
    unit_of_measurement: "VA"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Load Frequency"
    id: "${entities_id_prefix}_Load_Frequency"
    register_type: holding
    address: 655
    unit_of_measurement: "Hz"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD