sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Power PV1"
    id: "${entities_id_prefix}_Solar_Power_PV1"
    register_type: holding
    address: 672
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: power
    accuracy_decimals: 0
    value_type: U_WORD



  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Power PV2"
    id: "${entities_id_prefix}_Solar_Power_PV2"
    register_type: holding
    address: 673
    unit_of_measurement: "W"
    state_class: "measurement"
    device_class: power
    accuracy_decimals: 0
    value_type: U_WORD


  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Voltage PV1"
    id: "${entities_id_prefix}_Solar_Voltage_PV1"
    register_type: holding
    address: 676
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Voltage PV2"
    id: "${entities_id_prefix}_Solar_Voltage_PV2"
    register_type: holding
    address: 678
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 0
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Current PV1"
    id: "${entities_id_prefix}_Solar_Current_PV1"
    register_type: holding
    address: 677
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Current PV2"
    id: "${entities_id_prefix}_Solar_Current_PV2"
    register_type: holding
    address: 679
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Daily Production PV"
    id: "${entities_id_prefix}_Solar_Daily_Production_PV"
    register_type: holding
    address: 529
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Daily Production PV1"
    id: "${entities_id_prefix}_Solar_Daily_Production_PV1"
    register_type: holding
    address: 530
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Daily Production PV2"
    id: "${entities_id_prefix}_Solar_Daily_Production_PV2"
    register_type: holding
    address: 531
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${entities_name_prefix}-Solar Total Production PV"
    id: "${entities_id_prefix}_Solar_Total_Production_PV"
    register_type: holding
    address: 534
    skip_updates: 10
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1